volumes:
  gitops-data:

services:
  git-server:
    build:
      context: .
      dockerfile: git-server/Dockerfile
    image: git-server:latest

  cloud-master:
    build:
      context: .
      dockerfile: cloud-master/Dockerfile
    image: cloud-master:latest
    volumes:
      - gitops-data:/gitops
    environment:
      - GIT_REMOTE=git://git-server/salt-states.git
      - GITOPS_COMMIT=CHANGE_ME
    depends_on:
      - git-server
    networks:
      - salt-net

  panelpc:
    build:
      context: .
      dockerfile: panelpc/Dockerfile
    image: panelpc:latest
    hostname: panelpc
    volumes:
      - gitops-data:/gitops
    environment:
      - GIT_REMOTE=git://git-server/salt-states.git
      - CLOUD_MASTER=cloud-master
      - GITOPS_COMMIT=CHANGE_ME
    depends_on:
      - cloud-master
    networks:
      - salt-net

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: worker:latest
    hostname: worker
    volumes:
      - gitops-data:/gitops
    environment:
      - PANEL_MASTER=panelpc
      - GITOPS_COMMIT=CHANGE_ME
    depends_on:
      - panelpc
    networks:
      - salt-net

networks:
  salt-net:
    driver: bridge
