volumes:
  gitops-data:

services:
  git-server:
    build:
      context: .
      dockerfile: git-server/Dockerfile
    ports:
      - "9418:9418"
    networks:
      - salt-net

  argocd:
    build:
      context: .
      dockerfile: argocd/Dockerfile
    volumes:
      - gitops-data:/gitops
      - ./argocd/application.yaml:/config/application.yaml:ro
    depends_on:
      - git-server
    networks:
      - salt-net

  cloud-master:
    build:
      context: .
      dockerfile: cloud-master/Dockerfile
    volumes:
      - gitops-data:/gitops
    environment:
      - GIT_REMOTE=git://git-server/salt-states.git
    depends_on:
      - git-server
      - argocd
    networks:
      - salt-net

  panelpc:
    build:
      context: .
      dockerfile: panelpc/Dockerfile
    hostname: panelpc
    volumes:
      - gitops-data:/gitops
    environment:
      - GIT_REMOTE=git://git-server/salt-states.git
      - CLOUD_MASTER=cloud-master
    depends_on:
      - cloud-master
    networks:
      - salt-net

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    hostname: worker
    volumes:
      - gitops-data:/gitops
    environment:
      - PANEL_MASTER=panelpc
    depends_on:
      - panelpc
    networks:
      - salt-net

networks:
  salt-net:
    driver: bridge
